
cmake_policy(SET CMP0057 NEW)

add_library(somelib SHARED empty.cpp)

install(TARGETS somelib EXPORT exp
  LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/lib
  ARCHIVE DESTINATION ${CMAKE_INSTALL_PREFIX}/lib
  RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin
  INCLUDES DESTINATION include
)

install(EXPORT exp DESTINATION ${CMAKE_INSTALL_PREFIX}/lib/cmake)
