include(RunCMake)

run_cmake(TargetNotFound)
run_cmake(AppendExport)
run_cmake(OldIface)
run_cmake(NoExportSet)
run_cmake(RelativeLibDir)
run_cmake(RelativeIncludeDestination-CMP0057-NEW)
run_cmake(RelativeIncludeDestination-CMP0057-OLD)
run_cmake(RelativeIncludeDestination-CMP0057-WARN)
